(package "SampleElispProject"
         "0.0.1"
         "Sample elis project")

(website-url "https://github.com/jorgenschaefer/emacs-buttercup")
(keywords "test")

(package-file "SampleElispProject.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)

(depends-on "emacs" "26.3")
