name: Test downstream Eask

permissions:
  actions: read
  checks: read
  contents: read
  deployments: none
  id-token: none
  issues: read
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

on:
  pull_request:
  push:
    branches:
      - 'master'
      - '*'
    paths-ignore:
      - 'bin/*'
      - 'docs/images/*'
      - 'docs/running-tests.md'
      - 'scripts'

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        emacs-version:
          - 26.3
          - 27.2
          - 28.2
          - 29.4
        experimental: [false]
        include:
        - os: ubuntu-latest
          emacs-version: snapshot
          experimental: true
        - os: macos-latest
          emacs-version: snapshot
          experimental: true
        # TODO: There is an upstream error on windows, ignore it for now.
        #- os: windows-latest
        #  emacs-version: snapshot
        #  experimental: true
        exclude:
          - os: macos-latest
            emacs-version: 26.3
          - os: macos-latest
            emacs-version: 27.2

    steps:
    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - uses: emacs-eask/setup-eask@master
      with:
        version: 'snapshot'

    - uses: actions/checkout@v4

    - name: Generate Eask-file to link
      run: eask init --from source buttercup.el

    - name: Test downstream Eask
      working-directory: ./tests/fixtures/SampleElispProject/
      run: |
        eask link add buttercup ../../../
        eask test buttercup
